# Generated by Django 6.0.6 on 2026-07-06 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField()),
                ('gravida', models.PositiveSmallIntegerField()),
                ('parity', models.PositiveSmallIntegerField()),
                ('lmp_date', models.DateField()),
                ('is_lmp_estimated', models.BooleanField(default=False)),
                ('edd_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('hospital', models.CharField(blank=True, max_length=150)),
                ('health_centre', models.CharField(blank=True, max_length=150)),
                ('health_post', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('woman', models.ForeignKey(limit_choices_to={'role': 'woman'}, on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
