# Generated by Django 6.0.6 on 2026-07-06 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregnancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancy',
            name='iron_folic_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='iron_folic_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='mebendazole_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='mebendazole_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='mms_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='mms_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='mosquito_net_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='mosquito_net_given',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ANCVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.PositiveSmallIntegerField()),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('mother_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mother_height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fetal_position', models.CharField(blank=True, max_length=100)),
                ('fetal_heartbeat', models.CharField(blank=True, max_length=50)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anc_visits', to='pregnancy.pregnancy')),
            ],
            options={
                'ordering': ['visit_number'],
                'unique_together': {('pregnancy', 'visit_number')},
            },
        ),
    ]
